* Yarr
Yet Another RSS Reader

Yarr is a small RSS reader we'll build using RxJS and ES2015 in this workshop session, with some spices:

- We'll not use any JS framework
- We'll use Virtual-DOM library for optimal DOM updates
- We'll use delegated events

** How to follow
If you're visiting this repo on Github, you can just change to different tags and read this readme file for every step, and go through the code as you wish.

If you want to follow the tutorial, follow the Tutorial section at the end of this document.

** Objective
*** Not using any framework
- *Focus only on FRP*

  The objective we want to achieve with this tutorial is to start thinking in terms of Observables (we'll come to them later). Using a framework would add another layer to worry about (slash learn). We wanna focus exclusively on FRP aspect of RxJS, and not let more than necessary abstractions from other systems hinder us.

- *Come up with a sane architecture by ourself*

  Not really the objective, more of a wish. Let's see if we can come up with a saner architecture without stressing it too much, without relying on a framework to force our hand to do it a certain way. You've been warned, I am a 100% self-taught, don't blame me if we end up with a pile of horseshit 😛

- *Fun*

  Let's just get out of the framework cage and take a breath in fresh air.

*** Using Virtual DOM
- *Focus only on FRP*

  Virtual DOM is awesome. It can do changes in rendered DOM much more optimally with much little effort (from our end). We don't want to get into the intricacies of doing *proper* DOM manipulations during the tutorial. We only have 90 minutes and we wanna focus on thinking in Observables.

  Moreover, Virtual-DOM actually help in creating a better architecture for our app. We'll see how.

*** Using delegated events
We'll see what they are and why we're using them later when we come to them.


At the end of the day, it's all a fun little app, and I expect you to have fun building it with me.

** Setup
Let's setup our project to get started.
*** Webpack
We'll use webpack as our build tool and development assistant. It'll serve many things:
- Transpile ES6 to ES5
- Compile SASS to CSS
- Concat and minify CSS/JS
- Provide live-reload
- Compile JSX-ish syntax to VDOM hyperscript (we'll discuss it in a minute)

You can have a look at `webpack.config.js` file to

** Tutorial
First this we need to do is clone this tutorial. This tutorial is written in steps. Each step is represented as a git tag. We can checkout to the tag we want, try to do the tasks for the step, commit them, and checkout to next step if you'd want to start with a fresh slate.

*** Clone this repo
#+begin_src bash
git clone https://github.com/channikhabra/yarr
#+end_src

*** Checkout to step 0
Now that we have the repo cloned, let's checkout to step 0 so we can start with the tutorial.
#+begin_src bash
git checkout
#+end_src
